run:
	python3 run.py -t
	python3 run.py -s
	python3 run.py -d

t:
	python3 run.py -t

s:
	python3 run.py -s

d:
	python3 run.py -d

D:
	python3 run.py -D

clean:
	rm  __pycache__ *.pyc
	rm ../model.pkl